
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Darwin - 24.6.0 - arm64
...
